name: Publish

on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Install Pandoc
        run: sudo apt-get install pandoc
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --no-audit
      - run: make public/index.html
      - name: Download reveal.js
        run: |
          wget https://github.com/hakimel/reveal.js/archive/master.tar.gz
          tar -xzvf master.tar.gz
          mv reveal.js-master public/reveal.js
      - name: Publish export to gh-pages
        run: |
          echo "machine github.com login authtoken password ${GITHUB_TOKEN}" > ~/.netrc
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          cd public
          git init
          git add ./*
          git commit -m '📦 publish latest export'
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git push -f origin HEAD:gh-pages
